### ISSUE TITLE
Функция сжатия js 

### ISSUE THREAD

**Issue by garmanika** [StarkElessar/gulp-2022#4]
Как отключить функцию сжатия js?

**Comment by StarkElessar** [comment]
Тебе нужно отключить минификацию? Или обработку вебпаком?

**Comment by garmanika** [comment]
минификацию

**Comment by StarkElessar** [comment]
в dev режиме нет минификации, посмотри таску в галпе и передай туда `true`. Но тебе вряд ли поможет остутствие минификации ибо вебпак и бабель обрабатывают файл js и вряд ли тебе будет что то там понятно)
![image](https://github.com/StarkElessar/gulp-2022/assets/87839232/7ce3b5bc-61a0-42c0-9db7-a61781f44a2d)
