### ISSUE TITLE
Создание спрайта

### ISSUE THREAD

**Issue by matoka02** [StarkElessar/gulp-2022#5]
В какую директорию закидывать svg, чтобы сформировать спрайт? 
Пробую в myproject\src\images, запускаю команду **npm run sprite** - новых файлов не создано ни в myproject\src\images, ни в myproject\dist\images.
Хотя в readme указана **npm run svgSprive**, в package.json - **npm run sprite**, первая команда не отрабатывает в терминале.

**Comment by Sonikflame** [comment]
Добрый день, в папке **src** создайте папку **icons** и туда файлы **svg** (svgIcons: `${srcFolder}/icons/*.svg`,)
А так, все пути можно посмотреть в файле **paths.js** или в самих тасках.

**Comment by matoka02** [comment]
>А так, все пути можно посмотреть в файле **paths.js** или в самих тасках.

Похоже, смотрела не туда) 
![image](https://github.com/StarkElessar/gulp-2022/assets/120492521/860eff0f-20a8-4108-a3d2-27f666f30117) 
Спасибо, получилось.
